name: alquran_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: 4.6.5
  get_storage: ^2.0.3
  lottie: 1.3.0
  pretty_dio_logger: ^1.1.1
  just_audio: 0.9.24
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

